# Generated by Django 5.1.3 on 2024-12-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_alter_meal_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="recipe",
            field=models.TextField(blank=True),
        ),
    ]
