# Generated by Django 5.1.3 on 2024-12-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_meal_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="tags",
        ),
    ]
