# Generated by Django 5.1.4 on 2024-12-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_mealproducts_amount'),
        ('tags', '0002_tag_inheritance_and_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.tag'),
        ),
    ]
