# Generated by Django 5.1.3 on 2024-12-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('client', 'Client'), ('dietitian', 'Dietitian'), ('admin', 'Admin')], max_length=10)),
                ('diet_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_plan.dietplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DietitianClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='dietitians', to='users.user')),
                ('dietitian', models.ForeignKey(blank=True, limit_choices_to={'role': 'dietitian'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.user')),
            ],
            options={
                'unique_together': {('dietitian', 'client')},
            },
        ),
    ]
