# Generated by Django 5.1.3 on 2024-12-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietitianclient',
            options={'verbose_name': 'Dietitian-Client Relationship', 'verbose_name_plural': 'Dietitian-Client Relationships'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('dietitian', 'Dietitian'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
