# Generated by Django 5.1.4 on 2024-12-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plan', '0006_dietplan_tags_alter_dietplan_author'),
        ('users', '0003_alter_dietitianclient_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='diet_plan.dietplan'),
        ),
    ]
