# Generated by Django 5.1.3 on 2024-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productnutrients_productnutrient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.IntegerField(choices=[(0, 'No Tags'), (1, 'Salt'), (2, 'Sugar'), (4, 'Fat'), (8, 'Processed Food'), (16, 'Additives'), (32, 'Gluten'), (64, 'Milk'), (128, 'Eggs'), (256, 'Nuts'), (512, 'Peanuts'), (1024, 'Sesame'), (2048, 'Soybeans'), (4096, 'Celery'), (8192, 'Mustard'), (16384, 'Lupin'), (32768, 'Fish'), (65536, 'Crustaceans'), (131072, 'Molluscs'), (262144, 'Vegan'), (524288, 'Vegetarian'), (1048576, 'Palm Oil')], default=0),
        ),
    ]
