# Generated by Django 5.1.3 on 2024-12-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_tags"),
        ("tags", "0002_tag_inheritance_and_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.tag"),
        ),
    ]
