# Generated by Django 5.1.3 on 2024-12-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="inheritance_AND_logic",
            field=models.BooleanField(
                default=False,
                help_text="Zaznacz, jezeli wszystkie obiekty podrzedne musza miec ten tag, aby obiekt nadrzedny go odziedziczyl.",
            ),
        ),
    ]
