# Generated by Django 5.1.3 on 2024-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.IntegerField(choices=[(1, 'Salt'), (2, 'Sugar'), (4, 'Fat'), (8, 'Processed Food'), (16, 'Additives'), (32, 'Gluten'), (64, 'Milk'), (128, 'Eggs'), (256, 'Nuts'), (512, 'Peanuts'), (1024, 'Sesame'), (2048, 'Soybeans'), (4096, 'Celery'), (8192, 'Mustard'), (16384, 'Lupin'), (32768, 'Fish'), (65536, 'Crustaceans'), (131072, 'Molluscs'), (262144, 'Vegan'), (524288, 'Vegetarian'), (1048576, 'Palm Oil')], default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlanMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10)),
                ('day_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('a.m. snack', 'A.M. Snack'), ('lunch', 'Lunch'), ('p.m. snack', 'P.M. Snack'), ('dinner', 'Dinner')], max_length=10)),
            ],
        ),
    ]
