# Generated by Django 5.1.3 on 2024-12-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_plan', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='dietplanmeals',
            name='diet_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_plan.dietplan'),
        ),
    ]
