# Generated by Django 5.1.3 on 2024-12-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_plan', '0002_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplanmeals',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='meals',
            field=models.ManyToManyField(through='diet_plan.DietPlanMeals', to='meals.meal'),
        ),
    ]
