# Generated by Django 5.1.4 on 2024-12-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plan', '0007_alter_dietplan_author'),
        ('tags', '0002_tag_inheritance_and_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.tag'),
        ),
    ]
